### ISSUE TITLE
Peer-to-Peer-Review 11/01/2022 

### ISSUE THREAD

**Issue by Nejjari001** [demix007/Leaderboard#6]
Hi @demix007,

Good job so far 👍🏼

![StandingOvationGIF](https://user-images.githubusercontent.com/64089437/188081492-924704fb-187e-4ea4-89b4-1c0aba19e2ce.gif)

 linter errors  ✔️
 reviewed project run on your machine  ✔️
Used best practices  ✔️
 Used Github Flow  ✔️
 Work documented professionally  ✔️
 Full Functional site  ✔️

**Comment by demix007** [comment]
## Hello @Nejjari001 👋🏼 ,

Thank you for the review.
